[project]
name = "rag-gis-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "google-genai>=2.18.1",
    "langchain>=1.3.15",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.3.3",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.16.0",
    "python-dotenv>=1.2.2",
    "sse-starlette>=3.4.8",
    "uvicorn>=0.52.3",
]

[project.scripts]
rag-gis-api = "rag_gis_api.app:main"
rag-gis-ingest = "rag_gis_api.scripts.ingest:main"
rag-gis-load-doc = "rag_gis_api.scripts.load_doc:main"
rag-gis-load-pdf = "rag_gis_api.scripts.load_pdf:main"
rag-gis-prompt = "rag_gis_api.scripts.prompt:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.3",
]
